// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_V853pvmRNLr1F22PUXYe0KTDtWLq5g',
    appId: '1:939177880837:web:b2920faf44120210a15b6c',
    messagingSenderId: '939177880837',
    projectId: 'quality-control-tracker-389614',
    authDomain: 'quality-control-tracker-389614.firebaseapp.com',
    databaseURL: 'https://quality-control-tracker-389614-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quality-control-tracker-389614.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OVbdpGtSO48Uq0kfbgPMW1SQZxa_kFs',
    appId: '1:939177880837:android:c00aa1092bd01c76a15b6c',
    messagingSenderId: '939177880837',
    projectId: 'quality-control-tracker-389614',
    databaseURL: 'https://quality-control-tracker-389614-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quality-control-tracker-389614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUgxOSYS0GnTU4eOxnF29TTXjeOx3Lm-o',
    appId: '1:939177880837:ios:ed5c2d8f9072ee7ba15b6c',
    messagingSenderId: '939177880837',
    projectId: 'quality-control-tracker-389614',
    databaseURL: 'https://quality-control-tracker-389614-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quality-control-tracker-389614.appspot.com',
    iosClientId: '939177880837-6q8c8c4j0sd2r4n7vqu67mmkmkntt9gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.qualityControlTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUgxOSYS0GnTU4eOxnF29TTXjeOx3Lm-o',
    appId: '1:939177880837:ios:a19062f7765616d1a15b6c',
    messagingSenderId: '939177880837',
    projectId: 'quality-control-tracker-389614',
    databaseURL: 'https://quality-control-tracker-389614-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quality-control-tracker-389614.appspot.com',
    iosClientId: '939177880837-qeql8cl1lesus9l2tl97qkjfuknlg7sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.qualityControlTracker.RunnerTests',
  );
}
